<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="DisSagligiTakip.Business\DisSagligiTakip.Business.csproj" />
    <ProjectReference Include="DisSagligiTakip.DataAccess\DisSagligiTakip.DataAccess.csproj" />
    <ProjectReference Include="DisSagligiTakip.Entities\DisSagligiTakip.Entities.csproj" />
  </ItemGroup>

  <!-- Program.cs dosyasını derlemeye açıkça dahil ediyoruz -->
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Controllers\**\*.cs" />
  </ItemGroup>

</Project>